#!/bin/bash
#SBATCH --partition=any
#SBATCH -J asep_run_v7_N=40_SY=0_SX=20
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8
#SBATCH --ntasks-per-node=1
#SBATCH --time=7-0
#SBATCH --mem=31G
#SBATCH --output=%x-%j.out 

cd ~
cd projects/cyclopeps/cyclopeps/
source ~/.bashrc

export MKL_NUM_THREADS=8
export OMP_NUM_THREADS=8

N=40
SX=20
SY=0
python scripts/asep/run.py $N $N $SX $SY | tee /central/groups/changroup/members/phelms/asep/v7/output/asep_run_${N}x${N}_SX${SX}_SY${SY}.txt
