#!/bin/bash
#SBATCH --partition=serial
#SBATCH -J asep_run_N=50_SY=0_SX=15
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-node=8
#SBATCH --time=5-0
#SBATCH --mem=31G
#SBATCH --output=%x-%j.out 

cd ~
cd projects/dev_cyclopeps/cyclopeps/
source ~/.bashrc

export MKL_NUM_THREADS=8
export OMP_NUM_THREADS=8

N=100
SX=15
SY=0
python scripts/asep/run.py $N $N $SX $SY | tee output/jun15/asep_run_${N}x${N}_SX${SX}_SY${SY}.txt
